Repository fabientownsend/lunchbot, pull requests merged in 2018-11, with the labels that each got.

#40 Fixes for the foreman filter command
  lib/commands/menu/set_menu.rb
  lib/commands/order/reminder.rb
  lib/foreman_checker.rb
  lib/models/apprentice.rb
  spec/commands/menu/set_menu_spec.rb
  spec/commands/order/reminder_spec.rb
  spec/message_handler_spec.rb
  spec/models/apprentice_spec.rb
Labels: bug

#27 Removes commands from the list
  lib/command_info.rb
  spec/message_handler_spec.rb
Labels: enhancement, good first issue

#58 Fix typos
  lib/command_info.rb
Labels: enhancement

#63 Update lunch counter to work with office filter (#47)
  lib/commands/order/all_food_orders.rb
  spec/commands/order/all_food_orders_spec.rb
Labels: feature
